title:            Benedikt Bünz's site
description:      Welcome to my site.
# Your site's domain goes here. Leave localhost server or blank when working locally.
url:              "https://cs.nyu.edu/~bb"
#url:               //bbu.nz
#http://localhost:5000
#https://jponttuset.github.io
disqus_shortname: benediktbnz

# Owner/author information
owner:
  name:           Benedikt Bünz
  avatar:         benedikt3.png
  bio:            Benedikt Bünz is an Assistant Professor of Computer Science at NYU Courant. He also cofounded and am the chief scientist of <a href="https://espressosys.com/">Espresso Systems</a>. He researches applied cryptography, consensus and game theory, especially as it relates to cryptocurrencies. His work focuses on enhancing the privacy, usability and security of blockchain protocols.  
  email:          bb@nyu.edu
  email2:         benedikt@espressosys.com
  # Social networking links are used in author-bio sidebar. Update and remove as you like.
  linkedin: buenz
  google_scholar: Hj82r7MAAAAJ
  github: bbuenz
  strava: 12017759
# Analytics and webmaster tools stuff goes here
google_analytics: UA-109194849-1
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
#bing_verify:

# Links to include in top navigation
# For external links add external: true
links:
  - title: Publications
    url: /#publications
  - title: Teaching
    url: /teaching/
  - title: Talks
    url: /talks/
  - title: Personal
    url: /personal/

  - title: Random
    url: /random/
    #  - title: Blog
    #external: true
    #url: "https://www.crazyguyonabike.com/doc/?o=tS&doc_id=18076&v=VC"

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    America/Los_Angeles
future:      true
#pygments:    true
highlighter: rouge
markdown:    kramdown
kramdown:
  extensions: ["strikethrough"]

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title/

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

  coderay:
    coderay_line_numbers:
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

plugins:
    - jekyll-font-awesome-sass
    - jekyll-bootstrap-sass

bootstrap:
  assets: true

font-awesome:
  assets: true
include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
